sudo: required
services:
  - docker

before_install:
  - docker build -t brunokiafuka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brunokiafuka/react-test yarn test

after_success:
  - docker build -t brunokiafuka/multi-client ./client
  - docker build -t brunokiafuka/multi-nginx ./nginx
  - docker build -t brunokiafuka/multi-server ./server
  - docker build -t brunokiafuka/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push brunokiafuka/multi-client
  - docker push brunokiafuka/multi-nginx
  - docker push brunokiafuka/multi-server
  - docker push brunokiafuka/multi-worker
